#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          nsaproxy
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Startup daemon script for nsaproxy
### END INIT INFO
#
set -e

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
DAEMONNAME=nsaproxy
DAEMON=/usr/bin/$DAEMONNAME
PIDFILE=/run/nsaproxy/$DAEMONNAME.pid
IOSCHED=idle
NICE=0
RUNASUSER=nsaproxy
EXTRA_OPTS=""

[ -r /etc/default/nsaproxy ] && . /etc/default/nsaproxy

[ "${NSAPROXY_ENABLE}" = "no" ] && exit 0

. /lib/lsb/init-functions

test -x $DAEMON || exit 0

case "$1" in
  start)
    log_daemon_msg "Starting nsaproxy" "$DAEMONNAME"
    if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE \
           --iosched $IOSCHED --nicelevel $NICE \
           --exec $DAEMON -- -p $PIDFILE $EXTRA_OPTS 2>/dev/null;
    then
        log_end_msg 0
    else
        log_end_msg 1
    fi
    ;;
  stop)
    log_daemon_msg "Stopping nsaproxy" "$DAEMONNAME"
    if start-stop-daemon --stop --quiet --oknodo --retry 5 --pidfile $PIDFILE --user $RUNASUSER;
    then
        log_end_msg 0
    else
        log_end_msg 1
    fi
    rm -f $PIDFILE
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON "$DAEMONNAME" && exit 0 || exit $?
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
