#!/bin/sh

set -e

case "$1" in
    configure)
        pip install -r /usr/share/nsaproxy/requirements.txt > /dev/null

        update-rc.d nsaproxy defaults

        if [ -f "/etc/nsaproxy/credentials.yml" ];
        then
            invoke-rc.d nsaproxy start || true
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
    ;;
esac
